"""empty message

Revision ID: c77146d2766c
Revises: 41a2559698fb
Create Date: 2022-08-04 03:39:14.553508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77146d2766c'
down_revision = '41a2559698fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_venue', sa.String(length=2), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_venue')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
